name: EPG Update for dens.tv

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"  # Runs every day at midnight

jobs:
  update_dens:
    name: EPG Update for dens.tv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v2
        with:
          repository: 'ZYGYU/epg'

      - name: Clone EPG Repository
        run: |
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git epg
          cd epg
          npm install

      - name: Generate EPG Output for dens.tv
        run: |
          cd epg
          npm run grab -- --site=dens.tv
          mv guide.xml ../channel/dens.tv.xml

      - name: Commit and Push EPG Output to Your Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add channel/dens.tv.xml
          git commit -m "Update EPG output for dens.tv [skip ci]"
          git push origin master
