name: EPG Update for mncvision.id

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 */3 * *"  # Runs every day at midnight

jobs:
  update_mncvision:
    name: EPG Update for mncvision.id
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v2
        with:
          repository: 'ZYGYU/epg'

      - name: Clone EPG Repository
        run: |
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git epg
          cd epg
          npm install

      - name: Generate EPG Output for mncvision.id
        run: |
          cd epg
          npm run grab -- --site=mncvision.id --lang=id --maxConnections=2 --days=3
          mv guide.xml ../channel/mncvision.id.xml

      - name: Commit and Push EPG Output to Your Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin master
          git stash  # Stash any local changes
          git pull origin master --rebase
          git stash pop  # Re-apply stashed changes after the pull
          git add channel/mncvision.id.xml
          git commit -m "Update EPG output for mncvision.id [skip ci]" || echo "No changes to commit"
          git push origin master
