name: EPG Update and Upload

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Adjust the schedule as needed

jobs:
  epg_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v2
        with:
          repository: 'ZYGYU/epg'  # Ensure it references your repository

      - name: Clone EPG Repository
        run: |
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git epg
          cd epg
          npm install

      - name: Generate EPG Output for player.ee.co.uk
        run: |
          cd epg
          npm run grab -- --site=player.ee.co.uk
          mv guide.xml ../  # Move guide.xml to your repository root directory

      - name: Commit and Push EPG Output to Your Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add guide.xml
          git commit -m "Update EPG output for player.ee.co.uk [skip ci]"
          git push origin main  # Change 'main' to the appropriate branch if necessary
