name: EPG Update and Upload

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Adjust schedule as needed

jobs:
  epg_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v2
        with:
          repository: 'ZYGYU/epg'  # Ensure it's your repository

      - name: Clone EPG Repository
        run: |
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git epg
          cd epg
          npm install

      - name: Generate EPG Output for player.ee.co.uk
        run: |
          cd epg
          npm run grab -- --site=player.ee.co.uk
          mv guide.xml ../channel/player.ee.co.uk.xml  # Move and rename file

      - name: Commit and Push EPG Output to Your Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add channel/player.ee.co.uk.xml
          git commit -m "Update EPG output for player.ee.co.uk [skip ci]"
          git push origin master  # Change to the correct branch if necessary
