name: EPG Update for vidio.com

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  update_vidio:
    name: EPG Update for vidio.com
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v2
        with:
          repository: 'ZYGYU/epg'

      - name: Clone EPG Repository
        run: |
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git epg
          cd epg
          npm install

      - name: Generate EPG Output for vidio.com
        run: |
          cd epg
          npm run grab -- --site=vidio.com --lang=id
          mv guide.xml ../channel/vidio.com.xml

      - name: Commit and Push EPG Output to Your Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add channel/vidio.com.xml
          git commit -m "Update EPG output for vidio.com [skip ci]"
          git push origin master
