name: EPG Update for visionplus.id

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight

jobs:
  update_visionplus:
    name: EPG Update for visionplus.id
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v2
        with:
          repository: 'ZYGYU/epg'

      - name: Clone EPG Repository
        run: |
          git clone --depth 1 -b master https://github.com/iptv-org/epg.git epg
          cd epg
          npm install

      - name: Generate EPG Output for visionplus.id
        run: |
          cd epg
          npm run grab -- --site=visionplus.id
          mv guide.xml ../channel/visionplus.id.xml

      - name: Commit and Push EPG Output to Your Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add channel/visionplus.id.xml
          git commit -m "Update EPG output for visionplus.id [skip ci]"
          git push origin master
